---
title: "Clean data per minute"
author: "Jean-Pierre"
date: '`r format(Sys.Date(), "%d %B %Y")`'
output:
  rmarkdown::html_document:
    theme: paper
    number_sections: false
---

```{r setup, include=FALSE}
rm(list = ls())
if (!require("tidyverse")) install.packages("tidyverse")
library("tidyverse")
if (!require("lubridate")) install.packages("lubridate")
library("lubridate")
if (!require("oce")) install.packages("oce")
library(oce)
if (!require("dygraphs")) install.packages("dygraphs")
library(dygraphs)
if (!require("tidyverse")) install.packages("tidyverse")
library(xts)
if (!require("curl")) install.packages("curl")
library(curl)
if (!require("readxl")) install.packages("readxl")
library(readxl)
if (!require("data.table")) install.packages("data.table")
library(data.table)
if (!require("tsibble")) install.packages("tsibble")
library(tsibble)
if (!require("cowplot")) install.packages("cowplot")
library(cowplot)
if (!require("plotly")) install.packages("plotly")
library(plotly)
if (!require("htmlwidgets")) install.packages("htmlwidgets")
library(htmlwidgets)

if (Sys.getenv("LOGNAME") == "gattuso") path = "../../pCloud\ Sync/Documents/experiments/exp168_AWIPEV-CO2/fb_awipev-co2_server/ny-alesund/data/NRT_data/"
#if (Sys.getenv("LOGNAME") == "samir") path = "../../pCloud\ Sync/exp168_AWIPEV-CO2/fb_data/compare_anomalize/"

data <- readRDS(file = paste0(path, "all_nydata_minute.rds"))

```

## Introduction


```{r pCO2, include=FALSE}
#clean <- function(x) {
n <- c(0.5, 1, 2, 4) # number of times sd
k <- c(15, 31, 61, 121, 241) # time window in min
grid <- as_tibble(expand.grid(n=n, k=k)) %>%
  dplyr::arrange(n)
res <- tibble(datetime = data$datetime)
nas <- NULL
param <- NULL
#summ <- tibble(.rows = 20)
for (i in 1:nrow(grid)) {
#  i <- 1
tmp <- oce::despike(
    x=data$PCO2_corr_contros_filtered,
    reference = "median",
    n = grid$n[i],
    k = grid$k[i],
    min = NA,
    max = NA,
    replace = "NA"
  )
new_col_name <- paste0("n", grid$n[i], "k", grid$k[i])
res <- dplyr::mutate(res, !!new_col_name := tmp)
param <- append(param, new_col_name) # list of new columns
nas <- append(nas, sum(is.na(tmp))) # number of NAs in each cleaned column
nNAs <- tibble(param, nas)
}       
```

```{r plots, include=FALSE}
for (i in 1:length(param)) {
  y <- res[ , i + 1]
  n0.5k15 <- ggplot(data =res) +
    geom_point(aes(x=datetime, y=y)) +
    labs(title = param[i])
}
n2k15 <- ggplot() +
  geom_point(data =res, aes(x=datetime, y=n2k15))
g <- cowplot::plot_grid(n0.5k15, n2k15, ncol=1)




res_xts <- as.xts(res, order.by = res$datetime)
dygraph(res_xts, group = "", main=" ", ylab="pCO2") %>%
#dySeries("Sproct",  label = "Sproct", color = "red", strokeWidth = 0, pointSize=2) %>%
  dySeries("n0.5k15", label="pCO2", color = "black", strokeWidth = 0, pointSize=4) %>%
#dySeries( "sal_fb_filtered", label = "sal_fb_filtered",  color = "red", strokeWidth = 0, pointSize=2) %>%
 # dySeries("sal_insitu_filtered", label = " sal_insitu_filtered",color = "green", strokeWidth = 0, pointSize=0.5) %>%
  #dySeries("Sprim2beamZ_interp", label = "Sprim2beamZ_interp",color =" grey", strokeWidth = 0, pointSize=1) %>%
 #dyAxis("y",valueRange = c(-3, 8)) %>%
  dyLimit(0,color = "black", strokePattern ="dashed") %>%
  dyHighlight(highlightCircleSize = 8, highlightSeriesBackgroundAlpha = 0.2, hideOnMouseOut = TRUE) %>%
  dyOptions(useDataTimezone = TRUE,drawGrid = TRUE, drawPoints = TRUE, strokeWidth= 0, digitsAfterDecimal = 5) %>%
  dyRangeSelector(height = 30)


```




```{r despike, include=FALSE}
data <- data %>%     
   dplyr::mutate(#PCO2_Corr_filtered= despike(data$PCO2_Corr, reference= "median", n=0.5, k=121, replace="NA"),
                 PCO2_corr_contros_filtered= despike(data$PCO2_corr_contros, reference= "median", n=1.8, k=155, replace="NA"),
                 PCO2_clean_filtered= despike(data$PCO2_clean, reference= "median", n=1.8, k=155, replace="NA"),
                 PCO2_clean_2_filtered= despike(data$PCO2_clean_2, reference= "median", n=1.8, k=155, replace="NA"),
                 #temp_fb_filtered= despike(data$temp_fb, reference= "median", n=1, k=65, replace="NA"),
                 #AT_filtered= despike(data$AT, reference= "median", n=0.5, k=121, replace="NA"),
                 #phINT_filtered= despike(data$phINT, reference= "median", n=8, k=241, replace="NA"),
                 #phEXT_filtered= despike(data$phEXT, reference= "median", n=8, k=241, replace="NA"),
                 #HW_pH1_filtered= despike(data$HW_pH1, reference= "median", n=8, k=241, replace="NA"),
                 #HW_Temperature1_filtered= despike(data$HW_Temperature1, reference= "median", n=1, k=65, replace="NA"),
                 #temp_insitu_11m_filtered= despike(data$temp_insitu_11m, reference= "median", n=0.5, k=65, replace="NA"),
                 #pressure_insitu_ctd_filtered= despike(data$pressure_insitu_ctd, reference= "median", n=1, k=65, replace="NA"),
                 #par_insitu_profile_filtered= despike(data$par_insitu_profile, reference= "median", n=1, k=65, replace="NA"),
                 #par_insitu_10m_filtered= despike(data$par_insitu_10m, reference= "median", n=1, k=65, replace="NA"),
                 #par_air_filtered= despike(data$par_air, reference= "median", n=1, k=65, replace="NA"),
                 #turb_fb_filtered= despike(data$turb_fb, reference= "median", n=1, k=65, replace="NA"),
                 #temp_insitu_ctd_filtered= despike(data$temp_insitu_ctd, reference= "median", n=1, k=65, replace="NA"),
                 date = as.Date(data$datetime),
                 hour = hour(data$datetime)
  )

```

```{r hour format, include=FALSE}

# use this to make test with PCO2_clean from anomalize
selected_data_minute <- data # %>%
  # dplyr::select( datetime,
  #                PCO2_corr_contros_filtered,
  #                PCO2_corr_contros_approx,
  #                PCO2_corr_contros,
  #                PCO2_clean,
  #                observed,
  #                date,
  #                hour)

# use this to make test with PCO2_clean from anomalize
selected_data_hour <- as_tibble(selected_data_minute)%>%
  dplyr::group_by( date, hour) %>%
  dplyr::summarise(PCO2_corr_contros_filtered= mean(PCO2_corr_contros_filtered, na.rm = TRUE),
                   PCO2_clean= mean(PCO2_clean, na.rm = TRUE),
                   observed= mean(observed, na.rm = TRUE),
                   PCO2_corr_contros_approx= mean(PCO2_corr_contros_approx, na.rm = TRUE),
                   observed_PCO2_clean= mean(observed_PCO2_clean, na.rm = TRUE),
                   PCO2_clean_approx= mean(PCO2_clean_approx, na.rm = TRUE),
                   PCO2_corr_contros= mean(PCO2_corr_contros, na.rm = TRUE),
                   PCO2_clean_2= mean(PCO2_clean_2, na.rm = TRUE),
                  PCO2_clean_filtered= mean(PCO2_clean_filtered, na.rm = TRUE),
                  PCO2_clean_2_filtered = mean(PCO2_clean_2_filtered, na.rm = TRUE)) %>%
  dplyr::mutate(datetime = ymd_h(paste(date, hour, sep=" ", tz = "UTC"))) %>%
  dplyr::ungroup() %>% # this is to be able to perform the following changes
  dplyr::select(datetime, everything()) %>%
  dplyr::select(-c( hour)) %>% # not needed in the shiny display
  dplyr::arrange(desc(datetime))

# HOUR format
d_hour <- selected_data_hour

```

```{r plot format, , echo=FALSE, warning=FALSE, out.width= "100%"}
at_contros_cleaned_xts <- dplyr::select(d_hour,datetime, PCO2_corr_contros_approx, PCO2_corr_contros , PCO2_clean,PCO2_clean_2, PCO2_clean_approx, PCO2_corr_contros_filtered, PCO2_clean_filtered,  PCO2_clean_2_filtered)
at_contros_cleaned_xts <- as.xts(at_contros_cleaned_xts, order.by = d_hour$datetime)

dygraph(at_contros_cleaned_xts, group = "", main=" 2 anomalize : Frq 1 day - Trend 1 month  + Frq 1 hour - Trend 1 day", ylab="Ppco2") %>%
dySeries("PCO2_corr_contros",  label = "PCO2_corr_contros", color = "black", strokeWidth = 0, pointSize=4) %>%
  dySeries("PCO2_corr_contros_approx", label=" PCO2_corr_contros_approx", color = "blue", strokeWidth = 0, pointSize=2) %>%
dySeries( "PCO2_clean", label = "PCO2_clean",  color = "red", strokeWidth = 0, pointSize=2) %>%
  dySeries("PCO2_clean_2", label = " PCO2_clean_2",color = "green", strokeWidth = 0, pointSize=1) %>%
  dySeries("PCO2_clean_approx", label = "PCO2_clean_approx",color =" orange", strokeWidth = 0, pointSize=1) %>%
   
   dySeries("PCO2_corr_contros_filtered", label = " despike n = 1.8 + k = 155",color = "pink", strokeWidth = 0, pointSize=1) %>%
      dySeries("PCO2_clean_filtered", label = " PCO2_clean_despike ",color = "grey", strokeWidth = 0, pointSize=1) %>%
    dySeries("PCO2_clean_2_filtered", label = " PCO2_clean_2_despike",color = "yellow", strokeWidth = 0, pointSize=1) %>%

 #dyAxis("y",valueRange = c(-3, 8)) %>%
  dyLimit(0,color = "black", strokePattern ="dashed") %>%
  dyHighlight(highlightCircleSize = 8, highlightSeriesBackgroundAlpha = 0.2, hideOnMouseOut = TRUE) %>%
  dyOptions(useDataTimezone = TRUE,drawGrid = TRUE, drawPoints = TRUE, strokeWidth= 0, digitsAfterDecimal = 5) %>%
  dyRangeSelector(height = 30)



## plot 2
at_contros_cleaned_xts <- dplyr::select(d_hour,datetime, PCO2_corr_contros , PCO2_clean,PCO2_clean_2)
at_contros_cleaned_xts <- as.xts(at_contros_cleaned_xts, order.by = d_hour$datetime)

dygraph(at_contros_cleaned_xts, group = "", main=" 2 anomalize : Frq 1 day - Trend 1 month  + Frq 1 hour - Trend 1 day", ylab="Ppco2") %>%
dySeries("PCO2_corr_contros",  label = "PCO2_corr_contros", color = "black", strokeWidth = 0, pointSize=4) %>%
dySeries( "PCO2_clean", label = "PCO2_clean",  color = "red", strokeWidth = 0, pointSize=2) %>%
dySeries("PCO2_clean_2", label = " PCO2_clean_2",color = "green", strokeWidth = 0, pointSize=1) %>%
 #dyAxis("y",valueRange = c(-3, 8)) %>%
  dyLimit(0,color = "black", strokePattern ="dashed") %>%
  dyHighlight(highlightCircleSize = 8, highlightSeriesBackgroundAlpha = 0.2, hideOnMouseOut = TRUE) %>%
  dyOptions(useDataTimezone = TRUE,drawGrid = TRUE, drawPoints = TRUE, strokeWidth= 0, digitsAfterDecimal = 5) %>%
  dyRangeSelector(height = 30)
```


